Fix Unexpected value type error
`assembly._assembly_config_struct` raises the following error when
merging 2 lists:

```
  File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/pyartcd/pyartcd/util.py", line 89, in get_assembly_promotion_permits
    return assembly._assembly_config_struct(model.Model(releases_config), assembly_name, 'promotion_permits', [])
  File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/doozer/doozerlib/assembly.py", line 231, in _assembly_config_struct
    key_struct = merger(key_struct, parent_config_struct.primitive() if hasattr(parent_config_struct, "primitive") else parent_config_struct)
  File "/mnt/workspace/jenkins/working/cd-builds_build_promote-assembly@2/art-tools/doozer/doozerlib/assembly.py", line 102, in merger
    raise TypeError(f'Unexpected value type: {type(a)}: {a}')
TypeError: Unexpected value type: <class 'doozerlib.model.ListModel'>: [{'code': 'ATTACHED_BUGS', 'why': 'CVE tracker validation does not yet understand links from jira to bugzilla, this has been humanly validated this time'}]
```

ListModel needs to be converted to its primitive type `list` before calling `merger`.