prepare-release: Fix undefined attribute error
Fix `AttributeError: 'PrepareReleasePipeline' object has no attribute 'assembly_name'`.

Also don't mention assembly defination for `stream` assembly, which is used in 3.11.