prepare-release: Fix ImportError
Fixes the following error:
```python
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/pyartcd/pyartcd/__main__.py", line 4, in <module>
    from pyartcd.pipelines import (prepare_release, promote, rebuild,
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/pyartcd/pyartcd/pipelines/prepare_release.py", line 27, in <module>
    from pyartcd.util import (get_assembly_basis, get_assembly_type,
ImportError: cannot import name 'go_suffix_for_arch'
```

It turns out go_suffix_for_arch was removed from pyartcd.util by this commit: https://github.com/openshift/aos-cd-jobs/commit/7c0da6922ea9f4ef45a436e265b5ff2f7dd4491f#diff-6a68c2ae2c26daa692da9c2b42a8e7a6d88d9e73f7b505e4afddbb8c0dfc673eR8-R10
When I worked on this PR https://github.com/openshift/aos-cd-jobs/pull/3028, I didn’t have that above commit pulled.

This PR fixes the issue by importing `go_suffix_for_arch` directly from
`doozerlib.util`.