Fix build issue on python3.13
Ran into this error while building pydantic on python3.13:

```
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
```
Recent versions do not have it.
Also, set lower boud for pip-system-certs, as the 5.1 issue is solved in
5.2.