attach-cve-flaws: fix CVEs not associated error
There is an issue with the order of converting RHBA to RHSA and
associate CVEs with builds. We need to do it in the correct order and
ensure that the association for JIRA bugs and bugzilla bugs don't
override each other.

https://saml.buildvm.hosts.prod.psi.bos.redhat.com:8888/job/aos-cd-builds/job/build%252Fprepare-release/481/console
```
2022-09-15 06:41:40,996 ERROR Traceback (most recent call last):
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/attach_cve_flaws_cli.py", line 128, in get_flaws
    await associate_builds_with_cves(errata_api, advisory, attached_tracker_bugs, tracker_flaws, flaw_id_bugs, noop)
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/cli/attach_cve_flaws_cli.py", line 165, in associate_builds_with_cves
    await AsyncErrataUtils.associate_builds_with_cves(errata_api, advisory.errata_id, attached_builds, cve_components_mapping, dry_run=dry_run)
  File "/mnt/workspace/jenkins/working/_cd-builds_build_prepare-release/art-tools/elliott/elliottlib/errata_async.py", line 144, in associate_builds_with_cves
    raise ValueError(f"The following CVEs are not associated with advisory {advisory_id}: {', '.join(sorted(extra_cves))}")
ValueError: The following CVEs are not associated with advisory 101901: CVE-2022-34177, CVE-2022-36881
```